#!/usr/bin/env bash
# ============================================================
# DXN1 STUDIO 3 — one-line installer. Fully native, fully C++23.
#
#    curl -fsSL https://raw.githubusercontent.com/DXN1-termux/DXN1-STUDIO/master/scripts/install.sh | bash
#
# What it does:
#   1. checks the tools (git; a C++23 compiler — g++ or clang++)
#   2. clones STUDIO 3 into ~/dxn1-studio-3 (or updates it)
#   3. builds the native core (make -C native) and runs the engine
#      selftest, so you know it's green before you play
#   4. writes a `dxn3` launcher into ~/.local/bin
#
# There is no Electron, no Node and no Python in this repo. The studio
# is one C++23 binary; the only dependency is libstdc++.
#
# Flags:  --dir X  install into X (default ~/dxn1-studio-3)
#         --dir=X  same, = form
#         --run    launch STUDIO 3 when the installer finishes
# The script prints every step and never touches anything outside
# its install directory and ~/.local/bin (the dxn3 launcher).
# ============================================================
set -u

REPO_URL="https://github.com/DXN1-termux/DXN1-STUDIO.git"
DEFAULT_DIR="$HOME/dxn1-studio-3"
INSTALL_DIR="$DEFAULT_DIR"
WANT_RUN=0

# --- curl|bash safe: read flags, never stdin -----------------
_args=("$@")
for ((i=0; i<${#_args[@]}; i++)); do
  case "${_args[$i]}" in
    --run) WANT_RUN=1 ;;
    --dir) [ $((i+1)) -lt ${#_args[@]} ] && { INSTALL_DIR="${_args[$((i+1))]}"; ((i++)); } ;;
    --dir=*) INSTALL_DIR="${_args[$i]#--dir=}" ;;
    -h|--help) sed -n '2,26p' "$0"; exit 0 ;;
  esac
done

C_G="\033[32m"; C_B="\033[36m"; C_Y="\033[33m"; C_R="\033[31m"; C_D="\033[2m"
say()  { printf "%b\n" "$1"; }
ok()   { say "  ${C_G}✔${C_D} $1"; }
warn() { say "  ${C_Y}▲${C_D} $1"; }
bad()  { say "  ${C_R}✘${C_D} $1"; }

say ""
say "${C_B}  ╭──────────────────────────────────────────╮"
say "${C_B}  │   DXN1  STUDIO  3   —   installer        │"
say "${C_B}  │   native C++23 · terminal truecolor      │"
say "${C_B}  ╰──────────────────────────────────────────╯${C_D}"
say "${C_D}  code · games · one binary${C_D}"
say ""

# --- 1. tool check -------------------------------------------
have() { command -v "$1" >/dev/null 2>&1; }
MISSING=0
if have git; then ok "git $( git --version 2>&1 | head -1 )"; else bad "git not found"; MISSING=1; fi
CXX_BIN=""
if have g++; then CXX_BIN=g++
elif have clang++; then CXX_BIN=clang++
fi
if [ -n "$CXX_BIN" ]; then
  ok "$CXX_BIN $( $CXX_BIN --version 2>&1 | head -1 )"
  if printf 'int main(){}' | $CXX_BIN -x c++ -std=c++23 - -o /tmp/dxn3_cxx_probe.$$ 2>/dev/null; then
    ok "C++23 compiles"
    rm -f /tmp/dxn3_cxx_probe.$$
  else
    warn "$CXX_BIN rejects -std=c++23 — the build may fail (needs GCC 12+ / clang 17+)"
  fi
else
  bad "no C++ compiler found (need g++ or clang++ with C++23)"
  MISSING=1
fi
if [ $MISSING -eq 1 ]; then
  say ""
  bad "install the tools above, then re-run this installer."
  exit 1
fi

# --- 2. clone / update ---------------------------------------
if [ -d "$INSTALL_DIR/.git" ]; then
  say ""
  say "${C_B}→ updating existing install in $INSTALL_DIR${C_D}"
  git -C "$INSTALL_DIR" fetch --depth 1 origin master >/dev/null 2>&1 \
    && git -C "$INSTALL_DIR" reset --hard origin/master >/dev/null 2>&1 \
    && ok "updated to origin/master" \
    || warn "update failed — keeping your current copy"
else
  say ""
  say "${C_B}→ cloning into $INSTALL_DIR${C_D}"
  if git clone --depth 1 "$REPO_URL" "$INSTALL_DIR" 2>/dev/null; then
    ok "cloned"
  else
    bad "clone failed — check your network and the repo URL"
    exit 1
  fi
fi

# --- 3. build + selftest -------------------------------------
say ""
say "${C_B}→ building the native core (takes ~10 seconds)${C_D}"
if ( cd "$INSTALL_DIR" && make -s -C native ) >/tmp/dxn3_install_build.log 2>&1 \
   && [ -x "$INSTALL_DIR/native/build/dxn3-native" ]; then
  ok "native core built — one binary, zero dependencies"
else
  say "   build log (tail):"
  tail -8 /tmp/dxn3_install_build.log 2>/dev/null | sed 's/^/     /'
  bad "the native core did not build — please open an issue with the log above"
  exit 1
fi
say "${C_D}→ running the engine selftest${C_D}"
if ( cd "$INSTALL_DIR" && native/build/dxn3-selftest ) >/tmp/dxn3_install_test.log 2>&1; then
  ok "$(tail -1 /tmp/dxn3_install_test.log)"
else
  bad "selftest failed?!"
  tail -5 /tmp/dxn3_install_test.log 2>/dev/null | sed 's/^/     /'
  exit 1
fi

# --- 4. the dxn3 launcher ------------------------------------
BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR" 2>/dev/null || BIN_DIR="/usr/local/bin"
LAUNCHER="$BIN_DIR/dxn3"
cat > "$LAUNCHER" << LAUNCH
#!/usr/bin/env bash
# DXN1 STUDIO 3 launcher (generated by install.sh) — the native studio
DIR="$INSTALL_DIR"
SCENE="\$1"
if [ -z "\$SCENE" ] && [ -f "\$DIR/scenes/playground.dxn1.json" ]; then
  SCENE="\$DIR/scenes/playground.dxn1.json"   # play from any directory
fi
if [ -n "\$SCENE" ] && [ ! -f "\$SCENE" ] && [ -f "\$DIR/\$SCENE" ]; then
  SCENE="\$DIR/\$SCENE"          # scenes resolve from the install root too
fi
exec "\$DIR/native/build/dxn3-native" \${SCENE:+--scene "\$SCENE"}
LAUNCH
chmod +x "$LAUNCHER"
case ":$PATH:" in *":$BIN_DIR":*) ok "launcher at $LAUNCHER" ;;
  *) ok "launcher at $LAUNCHER (add $BIN_DIR to PATH if the next step fails)" ;;
esac

# --- done ----------------------------------------------------
say ""
say "${C_G}  ✔ STUDIO 3 is installed — one C++23 binary, zero dependencies${C_D}"
say ""
say "  ${C_B}play it:${C_D}"
say "      dxn3                              ${C_D}# the title card, then the playground${C_D}"
say "      dxn3 scenes/level-1.dxn1.json     ${C_D}# any scene${C_D}"
say "      dxn3 --list-scenes                ${C_D}# what's installed${C_D}"
say ""
say "  ${C_B}keys:${C_D}  ${C_D}a/d run · w/space jump · r reset · +/- zoom · f fit${C_D}"
say "      ${C_D}tab inspect · e read the scene · p screenshot · q quit${C_D}"
say "  ${C_B}cmds:${C_D}  ${C_D}: opens the command bar — :scene :zoom :fit :w :screenshot :help${C_D}"
say ""

if [ "$WANT_RUN" = "1" ]; then
  say "${C_B}→ launching STUDIO 3…${C_D}"
  ( cd "$INSTALL_DIR" && exec ./native/build/dxn3-native )
fi
